---
title: "README"
author: "Amy Jung"
date: "10/14/2021"
output: html_document
---

# IDH1 Visualization Graphs

## Background

Glioblastomas (GBMs) are one of the most lethal types of cancer with low survival rate. GBMs are split into two categories: primary and secondary. The former is more common, is generally found in older individuals, and has a poorer prognosis. Among the many genes that are often mutated in GBMs is isocitrate dehydrogenase (IDH). More recently, mutations to IDH have been used as a prognostic biomarker. Three IDH isoforms exist, but IDH1/2 are more prevalent in GBMs.

## Requirements

This project creates simple graphs to visualize basic mutation information about IDH1, such as types of mutations and consequences, similar to what can be found on the International Cancer Genome Consortium's (ICGC) data portal. IDH1 mutation data was downloaded as a `.tsv` file from ICGC's portal on 10/14/2021. R version 4.0.4 (2021-02-15) was used for this project.

## Downloading Data from ICGC

1) Visit ICGC's website and search "IDH1", then click on the gene
2) Click on the "mutations" tab
3) Filter for "Brain" as "Primary Site" on the left-hand sidebar
4) Scroll down and click on "Open in Advanced Search" under the "Most Frequent Somatic Mutations" section
5) Click on "Export Table as TSV" to download a TSV file of all mutations (71 mutations at time of download)

## Pie Charts

I began by creating pie charts to start off slow and try to really understand how to manipulate the data. Pie charts are *not recommended* graphs because they are not very meaningful. The three graphs I generated demonstrate a few reasons:

1) When multiple slices are close together, the labels are likely to overlap
* Rotating the chart fixed this issue, but this is not a guaranteed solution each time

2) It's easy to see that the "Upstream" slice is roughly 25% in the original pie chart but not as much when the chart was rotated 110 degrees

## Bar Graph

My original motivation for this project was to recreate the (interactive) bar graph found on ICGC's website. Bar graphs are a better representation of the distribution of consequences compared to pie charts. 

It is important to note that my graph's frequencies for upstream and downstream values do not match up with the numbers found on ICGC's bar graph. I am not sure what filter criteria they use to obtain the frequencies because many entries with upstream/downstream mutations were filtered out, but my script counts all mutations that had an upstream or downstream consequence.

